const DiagnosticTest = require("../../models/DiagnosticTest");

// Create Test Type
exports.createTestType = async (req, res) => {
  try {
    const {
      name,
      description,
      category,
      price,
      sampleTypes,
      instructions,
      parameters,
      availableDoctors,
      centerId,
    } = req.body;

    // testCode is auto-generated by the model pre-save hook
    const testType = await DiagnosticTest.create({
      name,
      description,
      category,
      price,
      sampleTypes,
      instructions,
      parameters: parameters || [],
      availableDoctors: availableDoctors || [],
      centerId: centerId || null,
    });

    res.status(201).json(testType);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Get All Test Types (optionally filtered by centerId)
exports.getAllTestTypes = async (req, res) => {
  try {
    const filter = {};
    if (req.query.centerId) {
      filter.centerId = req.query.centerId;
    }
    const testTypes = await DiagnosticTest.find(filter);
    res.json(testTypes);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Get Single Test Type
exports.getTestTypeById = async (req, res) => {
  try {
    const testType = await DiagnosticTest.findById(req.params.id);

    if (!testType) {
      return res.status(404).json({ message: "Test Type not found" });
    }

    res.json(testType);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Update Test Type
exports.updateTestType = async (req, res) => {
  try {
    const updatedTestType = await DiagnosticTest.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true }
    );

    if (!updatedTestType) {
      return res.status(404).json({ message: "Test Type not found" });
    }

    res.json(updatedTestType);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Delete Test Type
exports.deleteTestType = async (req, res) => {
  try {
    const deleted = await DiagnosticTest.findByIdAndDelete(req.params.id);

    if (!deleted) {
      return res.status(404).json({ message: "Test Type not found" });
    }

    res.json({ message: "Test Type deleted successfully" });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};